### PR TITLE
updated for new opencv

### PR DESCRIPTION
**Pull request by jmhessel**
opencv was changed, and with newer versions your scripts don't work anymore -- this small change fixes them. perhaps there's a smarter check that can be made to see what version is required, or you could just require opencv 3.X+ for your script.

### CODE REVIEW

**Comment by acdha** [comment]
Ah, thanks for the warning & extra thanks for the patch. If you have a second, does `cv2.__version__` still exist on OpenCV 3? If so, I could do something like `cv2.__version__.startswith('2.')` to choose which version of that code to use.

**Comment by jmhessel** [comment]
>>> import cv2
>>> cv2.__version__
'3.0.0-alpha'


Yup!

**Comment by acdha** [comment]
I just merged a modified version of your patch in cfe842c42f122d676924b16f8af30c2431f9cd5c with a simple version check to pick the new code. I've tested this under OpenCV 2.4.11 but have not yet tried this on 3.x (which is still compiling).

**Comment by acdha** [comment]
That took [a little longer than expected](https://github.com/Homebrew/homebrew-science/issues/2302) but I verified this works on OpenCV 3, too.

**Comment by acdha** [comment]
Thanks again for the patch!

**Comment by jmhessel** [comment]
No problem; thanks for writing this!

**Pull request closed without merging**
